<table class="table table-striped table-bordered table-hover">
    <?php foreach($users as $u){ ?>
        <tr>
            <td>
                <?php echo $u->getEmail();?>
            </td>
            <td>
                <button user_id="<?php echo $u->getId();?>" type="button" class="btn btn-outline btn-danger btn-xs delete-u-btn">
                    <i class="fa fa-times-circle"></i>
                </button>
            </td>
        </tr>
    <?php } ?>
</table>
<script>
    $(document).ready(function(){
        $(user.opt.deleteBtn).confirm({
            'title':'Confirmar:',
            'confirm':function(button){
                var user_id = $(button).attr("user_id");
                user.delete(user_id);
            },
            'confirmButton': "Si",
            'cancelButton': "No",
            'text': "Eliminar Usuario?"
        });
    });
</script>